### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by knightfall-cs** [BryghtShadow/xapktool#9]
PS D:\Programs\XAPKTool> python xapktool.py D:\Programs\XAPKTool\Android
Traceback (most recent call last):
  File "D:\Programs\XAPKTool\xapktool.py", line 102, in <module>
    main(sys.argv[1:])
  File "D:\Programs\XAPKTool\xapktool.py", line 98, in main
    xapk = XAPK(folder)
           ^^^^^^^^^^^^
  File "D:\Programs\XAPKTool\xapktool.py", line 14, in __init__
    self.folder = Path(folder)
                  ^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\pathlib.py", line 871, in __new__
    self = cls._from_parts(args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\pathlib.py", line 509, in _from_parts
    drv, root, parts = self._parse_args(args)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\pathlib.py", line 493, in _parse_args
    a = os.fspath(a)
        ^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not list

* I Have my APK & OBB Files in D:\Programs\XAPKTool\Android directory .
* Name of APK & OBB :
 Flight.apk & main.1.com.StupaX.Flight.obb
* I also tried running "python xapktool.py /Android"

Don't know what causing this syntax error any help?

**Comment by knightfall-cs** [comment]
To resolve this issue,
In xapktool.py line 96,
Change: `def main(*args):`  to: `def main(args):` (remove the '*')
- By doing this, you're explicitly extracting the first argument (the folder path) from the sys.argv list and passing it as a string to the XAPK constructor. This should resolve the "expected str, bytes or os.PathLike object, not list" error.

Now, when you run the script with the folder path as an argument:
`python xapktool.py /path/to/your/folder`
It should work without errors.
